---
title: "Power_Calculator"
author: "Nasimeh & Anastasia"
date: "7/5/2022"
output: html_document
---

```{r setup, include=FALSE}

#if (!requireNamespace("BiocManager", quietly = TRUE))
#install.packages("BiocManager")
#BiocManager::install(version = "3.15")
#BiocManager::install("limma")
#BiocManager::install()

library(limma)
library(CpGassoc)
library(caret)
library(ggplot2)
library(reshape)

```


```{r setup, include=FALSE}
#unzipping 

#import_data = function(zip_file){
#user_path = "/Users/sima/Documents/summer project/datsets/"
#print(user_path)
#unziped_files = unzip(zip_file, exdir = getwd())
#print(unziped_files)
#print(zip_file)
#return(unziped_files)
#}
#user_path = "/Users/sima/Documents/summer project/datsets/"
#temp = list.files(path=getwd(), pattern = "*.zip")
#print(temp)
#a = import_data(temp)
#simulations = apply(temp, import_data)
```


```{r setup, include=FALSE}
unzip_file = function(item){

temp = list.files(path=getwd(), pattern = paste0("SimMethyl_run_",item))
list_of_txts<-unzip(temp,exdir = getwd()) #,list=TRUE
file1 = read.table(list_of_txts[1])
file2 = read.table(list_of_txts[2])
file3 = read.table(list_of_txts[3], header = TRUE)
workflow = list(file1, file2, file3)
return(workflow)
}
```

```{r setup, include=FALSE}
run1 <- unzip_file(1)
run2 <- unzip_file(2)

saveRDS(data,"/Users/sima/Documents/forsklinje/testing.rds")
```

```{r setup, include=FALSE}
Get_all_zip = function(n_zip){
all_runs_output = list()
for (i in 1:n_zip){
  run = unzip_file(i)
  all_runs_output[[i]] = run
}
return(all_runs_output)
}
```


```{r setup, include=FALSE}

all_zips <- Get_all_zip(2)

```

```{r setup, include=FALSE}
extract_data_from_zip = function(all_runs_zip_num, zip_order_num, file_name){
file_name_to_extract = ifelse(file_name=="Simulated_data",1,ifelse(file_name=="truly_different_sites_indices",2,ifelse(file_name=="User_Parameters",3,warning("WRONG_file_name"))))
all_zip = Get_all_zip(all_runs_zip_num)
extracted_data = all_zip [[ zip_order_num]][[file_name_to_extract]]
return(extracted_data)
}

#works only for a multiple zip files, in the case of single zip returns a matrix not a data frame
```

```{r setup, include=FALSE}

Simulated_data <- extract_data_from_zip(all_zips,2,"Simulated_data")

```

```{r setup, include=FALSE}
#calculate_means <- function (beta_values_matrix) {
  # check stop if not() to make sure there are no non numeric values.
  #means <- rowMeans(beta_values_matrix, na.rm=TRUE)# if all values within a row are NA produces NaN
  #means <- na.omit(means) #add handling of NAs if values in the the vector are NAs
  #return(means)
#}
#healthy_mean = calculate_means(healthy)
#diseased_mean = calculate_means(diseased)

```

```{r setup, include=FALSE}
get_num_samp_per_group = function(all_zips, zip_file_order, simulated_data_frame){
user_parameters = extract_data_from_zip(all_zips, zip_file_order, "User_Parameters")
healthy_proportion = user_parameters$Value[user_parameters$Parameter == "Healthy proportion"]
n_Group1 = ncol(simulated_data_frame)*healthy_proportion
n_Group2 = ncol(simulated_data_frame)*(1-healthy_proportion)
num_groups = c(n_Group1,n_Group2)
return(num_groups)
}

```

```{r setup, include=FALSE} 

get_num_samp_per_group(all_zips,2, Simulated_data)

```

```{r setup, include=FALSE}

local_t_test = function(all_zips,zip_file_order){
simulated_data_frame = extract_data_from_zip(all_zips,zip_file_order,"Simulated_data")
n_samples_per_gr = get_num_samp_per_group(all_zips,zip_file_order,simulated_data_frame)
n_group1 = n_samples_per_gr[1]

store_all_p_val= c()
for(i in 1:nrow(simulated_data_frame)){
t_test_output = t.test(simulated_data_frame[i,1:n_group1],simulated_data_frame[i,(n_group1+1):ncol(simulated_data_frame)])
p_value = t_test_output$p.value
store_all_p_val[i] = p_value
}
method = t_test_output$method
all_p_values = as.data.frame(store_all_p_val)
names(all_p_values) = method
return(all_p_values)
}  

```



```{r setup, include=FALSE}
# #Kolmogorov-Smirnov Tests - non-parametric
#remember to use the input as M-values
# the test is different from t-test as it compares distribution functions of the two groups as opposed to 
# only mean values are compared in t-test.
local_Ks_test = function(all_zips,zip_file_order){
simulated_data_frame = extract_data_from_zip(all_zips,zip_file_order,"Simulated_data")
n_samples_per_gr = get_num_samp_per_group(all_zips,zip_file_order,simulated_data_frame)
n_group1 = n_samples_per_gr[1]

store_all_p_val= c()
for(i in 1:nrow(simulated_data_frame)){
  gr1 = as.numeric(simulated_data_frame[i,1:n_group1])
  gr2 = as.numeric(simulated_data_frame[i,(n_group1+1):ncol(simulated_data_frame)])
KS_test_output = ks.test(gr1,gr2,alternative = "two.sided", exact = TRUE)
p_value = KS_test_output$p.value
store_all_p_val[i] = p_value
}
method = KS_test_output$method
all_p_values = as.data.frame(store_all_p_val)
names(all_p_values) = method
return(all_p_values)
}

```

```{r setup, include=FALSE}
#Limma #bayesian based 

#Limma #bayesian based 

local_limma_test = function(all_zips,zip_file_order){
# model.matrix(~ simulated_data$Group2) - by manually
simulated_data_frame = extract_data_from_zip(all_zips,zip_file_order,"Simulated_data")
n_samples_per_gr = get_num_samp_per_group(all_zips,zip_file_order,simulated_data_frame)
n_group1 = n_samples_per_gr[1]
n_group2 = n_samples_per_gr[2]
Group1 = c(rep(1,n_group1),rep(0,n_group2))
Group2 = c(rep(0,n_group1),rep(1,n_group2))
design_matrix = as.data.frame(cbind(Group1,Group2)) 
contrast_matrix = makeContrasts(Diff = Group2 - Group1, levels = design_matrix)

#test 3 - limma 
fit1 <- lmFit(simulated_data_frame, design_matrix)
fit2 <- contrasts.fit(fit1, contrast_matrix)
fit3 <- eBayes(fit2)
limma_output = as.data.frame(fit3)
limma_Pvalues = as.data.frame(limma_output$p.value)
names(limma_Pvalues) = "limma"
return(limma_Pvalues)
}

```


```{r setup, include=FALSE}
#test-statistics for all Cpgs for each test
run_all_test = function(all_zips, zip_file_order){
t_test_ouput = local_t_test(all_zips, zip_file_order)
ks_output = local_Ks_test(all_zips, zip_file_order)
local_limma_output = local_limma_test(all_zips, zip_file_order)
all_test_output = cbind(t_test_ouput,ks_output,local_limma_output)
return(all_test_output)
}

all_test_output =run_all_test(all_zips, 2)
```

```{r setup, include=FALSE}
num_zip_file = length(all_zips)
#import data and create variable zip "all_zips"
#call function run_all_test(all_zips, )
#


```


```{r setup, include=FALSE}
#Needs to be fixed after returning from simulation
logit_transformation = function (Beta_matrix){
 Beta_matrix <- ifelse(as.matrix(Beta_matrix)>=1, 0.99, as.matrix(Beta_matrix))
 Beta_matrix <- ifelse(as.matrix(Beta_matrix)<=0, 0.00000000000000001, as.matrix(Beta_matrix))
  beta_transform = log2(Beta_matrix/(1-Beta_matrix))
  resturn(logit_transformation)
}

```


```{r setup, include=FALSE}
getadjustPval = function(p_val_vector){
  p_val_adjusted =p.adjust(p_val_vector, method = "BH")
  return(p_val_adjusted)
}

#When you adjust the p-values are more insignificant (penalty) 

p_val_adjust = apply(all_test_output,2, getadjustPval)
      
```


```{r setup, include=FALSE}
create_predicted_vector = function(p_val_vector){
  signif_threshold = 0.05
  boolian_signif_p_val= ifelse (p_val_vector<signif_threshold,0,1)
  boolian_signif_p_val = as.factor(boolian_signif_p_val)
#levels(boolian_signif_p_val) = c(1,0)
  return(boolian_signif_p_val)
}
```


```{r setup, include=FALSE}
create_expected_val_vector = function(p_val_df,all_runs_zip_num,zip_order_num){
  indices_truly_different = extract_data_from_zip(all_runs_zip_num,zip_order_num,"truly_different_sites_indices")
  indices_truly_different = indices_truly_different$V1
  
  indices_p_val_vector = seq(1, nrow(p_val_df), by=1)
  boolian_truly_modif = as.integer(!indices_p_val_vector %in% indices_truly_different)
  boolian_truly_modif = factor(boolian_truly_modif)
  return(boolian_truly_modif)
} 
#create_expected_val_vector(all_test_output$`Welch Two Sample t-test` ,2,2)
```

```{r setup, include=FALSE}
create_confusion_matrix = function(all_test_df, all_runs_zip_num, zip_order_num){
  expected = create_expected_val_vector(all_test_df, all_runs_zip_num, zip_order_num)
  confusion_matrix = list()
  for (i in 1:ncol(all_test_df)){
  predicted = create_predicted_vector(all_test_df[,i])
  confusion_matrix[[i]] = confusionMatrix(data= predicted, reference=expected) 
  }
  names(confusion_matrix) = names(all_test_df)
  return(confusion_matrix)
}

```


```{r setup, inc=lude=FALSE}
calc_empirical_marg_power = function(all_confusionMatrix_list){
  #marg_power_list = list()
  df_all_test = as.data.frame(matrix(data=NA, nrow=3,ncol=2))
  names(df_all_test) = c("Power", "test")
  df_all_test$test = c("t_test","KS_test", "limma")
  
  for (i in 1:length(all_confusionMatrix_list)){
  confusion_matrix = all_confusionMatrix_list[[i]]
  extract_confTable= table(confusion_matrix$table)
  false_negative = as.numeric(names(extract_confTable)[1])
  true_positive = as.numeric(names(extract_confTable)[2])
  false_positive = as.numeric(names(extract_confTable)[3])
  true_negtaive = as.numeric(names(extract_confTable)[4])
  power_calc_val = true_positive/(true_positive + false_negative)
  df_all_test$Power[i] = power_calc_val

  }
  return(df_all_test)
}
```



```{r setup, include=FALSE}
power_calc_multiple_runs = function(all_zips){
  df_all_test = as.data.frame(matrix(data=NA, nrow=3,ncol=3))
  names(df_all_test) = c("Power", "test", "ID")
  #df_all_test$test = c("t_test","KS_test", "limma")
  #ID = c()
  for (i in 1:all_zips){
    All_test = run_all_test(all_zips, i)
    confusion_matrix = create_confusion_matrix(All_test, all_zips, i)
    calc_power_value = calc_empirical_marg_power(confusion_matrix)
    calc_power_value$ID = rep(i,3) #adding new column with IDs (zip ID)
    df_all_test = rbind(df_all_test,  calc_power_value)
   # df_all_test$ID[i] = i
  }
  df_all_test=na.omit(df_all_test)
  #df_all_test = rbind(df_all_test,  user_parameters)
  return(df_all_test)
}

```

```{r setup, include=FALSE}
a=power_calc_multiple_runs(2)

```

```{r setup, include=FALSE}
get_all_parameters = function(all_zips){

temp_df = as.data.frame(matrix(data=NA, nrow=1,ncol=5))
names(temp_df) = c("n_samples", "n_CpGs", "healthy_proportion", "effect_size", "n_modified_CpGs")
ID = c()
for (i in 1:all_zips){
  ID[i] = i
    user_parameters = extract_data_from_zip(all_zips, i, "User_Parameters")
    user_parameters = t(user_parameters)
    user_parameters = user_parameters[-1,]
    temp_df = rbind(temp_df,  user_parameters)
}
  temp_df=na.omit(temp_df)
  temp_df$ID = ID
  temp_df$n_samples = as.numeric(temp_df$n_samples)
  temp_df$n_CpGs = as.numeric(temp_df$n_CpGs)
  temp_df$healthy_proportion = as.numeric(temp_df$healthy_proportion)
  temp_df$effect_size = as.numeric(temp_df$effect_size)
  temp_df$n_modified_CpGs = as.numeric(temp_df$n_modified_CpGs)

  return(temp_df)
}

```


```{r setup, include=FALSE}
merge_data = function(all_zips){
power_calc_val = power_calc_multiple_runs(all_zips)
parameters = get_all_parameters(all_zips)
output_df = merge(power_calc_val, parameters, by="ID")
return(output_df)
}

```


```{r setup, include=FALSE}
#visualisation


plot_results_for_paramter = function(data,parameter_modified_string){ # input for parametere_modified should be a string
    constant_parameters = data[,!names(data) %in% c(parameter_modified_string,"test","Power", "ID")]
const_param_1 = paste(names(constant_parameters)[1], constant_parameters[1,1], sep = " ")
const_param_2 = paste(names(constant_parameters)[2], constant_parameters[1,2], sep = " ") 
const_param_3 = paste(names(constant_parameters)[3], constant_parameters[1,3], sep = " ") 
const_param_4 = paste(names(constant_parameters)[4], constant_parameters[1,4], sep = " ") 


  fig = ggplot(data, aes(x=Power , y=n_samples, color = test)) +
    geom_line()+
    geom_point(aes(shape=test))+ 
  labs(x="Power",y="Samples") +
  theme_minimal() +
  theme(plot.margin = unit(c(0,1,0,0),"lines")) + #legend.position = c(x, y)) +
  coord_cartesian(clip = "off") +
  annotate(geom= "text", x = 1, y = 120, label= paste(const_param_1,"\n",
                                                      const_param_2,"\n",
                                                      const_param_3,"\n",
                                                      const_param_4,"\n"))
 
return(fig)
  }

plot_results_for_paramter(data, "n_samples", "Power", "test")
```


```{r setup, include=FALSE}
data
for (col in 1:ncol(data)){
  for (val in 1:)
  if (data[,col])
  
}
```

```{r setup, include=FALSE}

```

```{r setup, include=FALSE}

```

```{r setup, include=FALSE}

```